### PR TITLE
Fix Compounding WorkRequest Bug

### LINKED ISSUE #93: "Network error"
**Describe the bug**
When I open Stack app, I cannot browse anything because it says "Network error"

**To Reproduce**
1. Open Stack app
2. Press on a post
3. "Network error" Screenshot_20201021-145806_Stack
4.

**Expected behavior**
Load the content

**Screenshots**

**Device Info (please complete the following information):**
 - Device: Note 8
 - OS: Android 8.0
 - Browser: N/A
 - Version: 1.0.2 (12)

**Additional context**
This issue didn't exist when I first installed it

### PR DESCRIPTION
**Pull request by tylerbwong**
#### Description
Fixes #93.

Background work was not being enqueued as unique work. This meant that every time a user opened the app, a new set of `WorkRequest`s would get enqueued, but existing work requests would not be canceled. This was especially noticeable with `BookmarksWorker`, which is a `PeriodicWorkRequest` that ran every 8 hours. Every time a user opened the app, a new request would be scheduled to be run every 8 hours from that point.

The side-effects of this bug would be that work requests would compound and eventually attempt to make a large number of requests to the Stack Exchange API at once. This would result in 503s being returned and the "Network error" message to appear when making any API request.

This PR introduces a fix going forward that will check `WorkManager` for existing work based on new identifiers on each `WorkRequest`. If no currently enqueued work is found for any new identifier, cancel all `WorkRequests` since we can assume the user has a ton of non-unique work enqueued. Then schedule the unique work as normal (based on the `ExistingWorkPolicy`).

This overall disables offline bookmarks for now until a more sustainable solution is developed.

#### Checklist
- [x] I self reviewed the submitted code
- [x] I ran `./gradlew ktlintCheck detekt` before submitting this PR
- [x] I ran the app on a device/emulator or added unit tests to verify this change

### CODE REVIEW

File: app/src/main/kotlin/me/tylerbwong/stack/data/work/WorkScheduler.kt [hunk 1]
```diff
@@ -1,16 +1,47 @@
...
+     * @param lifecycleOwner The host [LifecycleOwner] that will be in charge of observing work info
+     * requests.
+     */
+    fun schedule(lifecycleOwner: LifecycleOwner) {
+        // TODO Delete this once enough people are on the new version
+        val validWorkRequest = workRequests.find {
+            it.identifier == BookmarksWorker.IDENTIFIER
+        } ?: return
+        val workInfoLiveData = workManager.getWorkInfosForUniqueWorkLiveData(
+            validWorkRequest.identifier
```
Comment (brittanyberlanga) [inline app/src/main/kotlin/me/tylerbwong/stack/data/work/WorkScheduler.kt:26]: Rather than finding the BookmarksWorker request and using its identifier, can we directly use `BookmarksWorker.IDENTIFIER` here?

**Review by brittanyberlanga — DISMISSED** [review]

**Review by brittanyberlanga — APPROVED** [review]
